runtime: python27
api_version: 1
threadsafe: false

# [START handlers]
handlers:

- url: /.*
  script: trading.py
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# - name: jinja2
#   version: latest
# [END libraries]
